---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: user-management
  namespace: kisanvedika
  annotations:
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`user.bighaat.cf`) && PathPrefix(`/user`)
    kind: Rule
    services:
    - name: user-management
      port: 80
